[package]
name = "sum"
version = "0.0.1"
edition = "2018"
authors = ["Mantre <mantre@protonmail.com>"]

[dependencies]
kelk = {path = "../../kelk"}

[lib]
name = "sum"
path = "lib.rs"
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
opt-level=3

[profile.dev]
panic = "abort"
