[package]
name = "calculator"
version = "0.0.1"
edition = "2018"
authors = ["Mantre <mantre@protonmail.com>"]

[dependencies]
kelk = { path = "../../kelk" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
schemars = "0.8"

[lib]
name = "calculator"
path = "lib.rs"

