[package]
name = "kelk"
version = "0.0.1"
edition = "2018"
authors = ["Mantre <mantre@protonmail.com>"]
license = "MIT"
repository = "https://github.com/zarbchan/kelk"
description = "Kelk is a Low-level interface for interacting with the smart contract Wasm executor."


[dependencies]
scale = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive", "full"] }


[profile.release]
lto = true